//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceEN", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 Account 的本地化字符串。
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string accountStatus {
            get {
                return ResourceManager.GetString("accountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Add Member 的本地化字符串。
        /// </summary>
        internal static string addMember {
            get {
                return ResourceManager.GetString("addMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Add Product 的本地化字符串。
        /// </summary>
        internal static string addProduct {
            get {
                return ResourceManager.GetString("addProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Increase Stock 的本地化字符串。
        /// </summary>
        internal static string addStock {
            get {
                return ResourceManager.GetString("addStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Add Administrator 的本地化字符串。
        /// </summary>
        internal static string addUser {
            get {
                return ResourceManager.GetString("addUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Administrator system 的本地化字符串。
        /// </summary>
        internal static string adminSystem {
            get {
                return ResourceManager.GetString("adminSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 All 的本地化字符串。
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Arrived 的本地化字符串。
        /// </summary>
        internal static string arrived {
            get {
                return ResourceManager.GetString("arrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Categories 的本地化字符串。
        /// </summary>
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Select a type first 的本地化字符串。
        /// </summary>
        internal static string chooseType {
            get {
                return ResourceManager.GetString("chooseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Creation Time 的本地化字符串。
        /// </summary>
        internal static string createdTime {
            get {
                return ResourceManager.GetString("createdTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Creator ID 的本地化字符串。
        /// </summary>
        internal static string createdUser {
            get {
                return ResourceManager.GetString("createdUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Account:  的本地化字符串。
        /// </summary>
        internal static string defaultAccount {
            get {
                return ResourceManager.GetString("defaultAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string del {
            get {
                return ResourceManager.GetString("del", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Delivery Method 的本地化字符串。
        /// </summary>
        internal static string deliveryMethod {
            get {
                return ResourceManager.GetString("deliveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Delivery Status 的本地化字符串。
        /// </summary>
        internal static string deliveryStatus {
            get {
                return ResourceManager.GetString("deliveryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Edit Product 的本地化字符串。
        /// </summary>
        internal static string editProduct {
            get {
                return ResourceManager.GetString("editProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 ID 的本地化字符串。
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Image 的本地化字符串。
        /// </summary>
        internal static string img {
            get {
                return ResourceManager.GetString("img", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string introduce {
            get {
                return ResourceManager.GetString("introduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Is Open 的本地化字符串。
        /// </summary>
        internal static string isOpen {
            get {
                return ResourceManager.GetString("isOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Level 的本地化字符串。
        /// </summary>
        internal static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Member Administrator 的本地化字符串。
        /// </summary>
        internal static string memberAdmin {
            get {
                return ResourceManager.GetString("memberAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Member system 的本地化字符串。
        /// </summary>
        internal static string memberSystem {
            get {
                return ResourceManager.GetString("memberSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Subtype 的本地化字符串。
        /// </summary>
        internal static string minorCategories {
            get {
                return ResourceManager.GetString("minorCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 No 的本地化字符串。
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Order ID 的本地化字符串。
        /// </summary>
        internal static string orderId {
            get {
                return ResourceManager.GetString("orderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Order Status 的本地化字符串。
        /// </summary>
        internal static string orderStatus {
            get {
                return ResourceManager.GetString("orderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Order system 的本地化字符串。
        /// </summary>
        internal static string orderSystem {
            get {
                return ResourceManager.GetString("orderSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Phone Number 的本地化字符串。
        /// </summary>
        internal static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Price 的本地化字符串。
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Product 的本地化字符串。
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Product Administrator 的本地化字符串。
        /// </summary>
        internal static string productAdmin {
            get {
                return ResourceManager.GetString("productAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Product ID 的本地化字符串。
        /// </summary>
        internal static string productId {
            get {
                return ResourceManager.GetString("productId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Product Image 的本地化字符串。
        /// </summary>
        internal static string productImg {
            get {
                return ResourceManager.GetString("productImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Product English Description 的本地化字符串。
        /// </summary>
        internal static string productIntroduceEN {
            get {
                return ResourceManager.GetString("productIntroduceEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Product Chinese Description 的本地化字符串。
        /// </summary>
        internal static string productIntroduceTW {
            get {
                return ResourceManager.GetString("productIntroduceTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Product English Name 的本地化字符串。
        /// </summary>
        internal static string productNameEN {
            get {
                return ResourceManager.GetString("productNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Product Name Search 的本地化字符串。
        /// </summary>
        internal static string productNameSelect {
            get {
                return ResourceManager.GetString("productNameSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Product Chinese Name 的本地化字符串。
        /// </summary>
        internal static string productNameTW {
            get {
                return ResourceManager.GetString("productNameTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Product Price 的本地化字符串。
        /// </summary>
        internal static string productPrice {
            get {
                return ResourceManager.GetString("productPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Stock 的本地化字符串。
        /// </summary>
        internal static string productStock {
            get {
                return ResourceManager.GetString("productStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Product systemc 的本地化字符串。
        /// </summary>
        internal static string productSystem {
            get {
                return ResourceManager.GetString("productSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Product Type 的本地化字符串。
        /// </summary>
        internal static string productType {
            get {
                return ResourceManager.GetString("productType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string pwd {
            get {
                return ResourceManager.GetString("pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Received 的本地化字符串。
        /// </summary>
        internal static string received {
            get {
                return ResourceManager.GetString("received", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Decrease Stock 的本地化字符串。
        /// </summary>
        internal static string reduceStock {
            get {
                return ResourceManager.GetString("reduceStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Returned 的本地化字符串。
        /// </summary>
        internal static string returned {
            get {
                return ResourceManager.GetString("returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Returning 的本地化字符串。
        /// </summary>
        internal static string returning {
            get {
                return ResourceManager.GetString("returning", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Roles 的本地化字符串。
        /// </summary>
        internal static string roles {
            get {
                return ResourceManager.GetString("roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Serial Number 的本地化字符串。
        /// </summary>
        internal static string serialNumber {
            get {
                return ResourceManager.GetString("serialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Shipped 的本地化字符串。
        /// </summary>
        internal static string shipped {
            get {
                return ResourceManager.GetString("shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Shipping 的本地化字符串。
        /// </summary>
        internal static string shipping {
            get {
                return ResourceManager.GetString("shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Sign out 的本地化字符串。
        /// </summary>
        internal static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Stock 的本地化字符串。
        /// </summary>
        internal static string stock {
            get {
                return ResourceManager.GetString("stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Super Administrator 的本地化字符串。
        /// </summary>
        internal static string superAdmin {
            get {
                return ResourceManager.GetString("superAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Welcome to the backend system 的本地化字符串。
        /// </summary>
        internal static string title1Default {
            get {
                return ResourceManager.GetString("title1Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Add User 的本地化字符串。
        /// </summary>
        internal static string titleAddUser {
            get {
                return ResourceManager.GetString("titleAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Edit User 的本地化字符串。
        /// </summary>
        internal static string titleEditUser {
            get {
                return ResourceManager.GetString("titleEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Login page 的本地化字符串。
        /// </summary>
        internal static string titleLogin {
            get {
                return ResourceManager.GetString("titleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Member Account 的本地化字符串。
        /// </summary>
        internal static string titleMember {
            get {
                return ResourceManager.GetString("titleMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Orders 的本地化字符串。
        /// </summary>
        internal static string titleOrder {
            get {
                return ResourceManager.GetString("titleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Administrator Account 的本地化字符串。
        /// </summary>
        internal static string titleUser {
            get {
                return ResourceManager.GetString("titleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Total Amount 的本地化字符串。
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Total Spent 的本地化字符串。
        /// </summary>
        internal static string totalSpent {
            get {
                return ResourceManager.GetString("totalSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Please enter account 的本地化字符串。
        /// </summary>
        internal static string txbAccount {
            get {
                return ResourceManager.GetString("txbAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Please enter password 的本地化字符串。
        /// </summary>
        internal static string txbPassword {
            get {
                return ResourceManager.GetString("txbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Administrator ID 的本地化字符串。
        /// </summary>
        internal static string userId {
            get {
                return ResourceManager.GetString("userId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Wallet 的本地化字符串。
        /// </summary>
        internal static string wallet {
            get {
                return ResourceManager.GetString("wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Return Requested 的本地化字符串。
        /// </summary>
        internal static string _return {
            get {
                return ResourceManager.GetString("return", resourceCulture);
            }
        }
    }
}
