//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 帳號 的本地化字符串。
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 狀態 的本地化字符串。
        /// </summary>
        internal static string accountStatus {
            get {
                return ResourceManager.GetString("accountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增會員 的本地化字符串。
        /// </summary>
        internal static string addMember {
            get {
                return ResourceManager.GetString("addMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增商品 的本地化字符串。
        /// </summary>
        internal static string addProduct {
            get {
                return ResourceManager.GetString("addProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加庫存量 的本地化字符串。
        /// </summary>
        internal static string addStock {
            get {
                return ResourceManager.GetString("addStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增管理員 的本地化字符串。
        /// </summary>
        internal static string addUser {
            get {
                return ResourceManager.GetString("addUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 管理員系統 的本地化字符串。
        /// </summary>
        internal static string adminSystem {
            get {
                return ResourceManager.GetString("adminSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 全部 的本地化字符串。
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已到貨 的本地化字符串。
        /// </summary>
        internal static string arrived {
            get {
                return ResourceManager.GetString("arrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 登入 的本地化字符串。
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 類型 的本地化字符串。
        /// </summary>
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 請先選擇類型 的本地化字符串。
        /// </summary>
        internal static string chooseType {
            get {
                return ResourceManager.GetString("chooseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 建立時間 的本地化字符串。
        /// </summary>
        internal static string createdTime {
            get {
                return ResourceManager.GetString("createdTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 建立者ID 的本地化字符串。
        /// </summary>
        internal static string createdUser {
            get {
                return ResourceManager.GetString("createdUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 帳號:  的本地化字符串。
        /// </summary>
        internal static string defaultAccount {
            get {
                return ResourceManager.GetString("defaultAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 刪除 的本地化字符串。
        /// </summary>
        internal static string del {
            get {
                return ResourceManager.GetString("del", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 配送方式 的本地化字符串。
        /// </summary>
        internal static string deliveryMethod {
            get {
                return ResourceManager.GetString("deliveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 配送狀態 的本地化字符串。
        /// </summary>
        internal static string deliveryStatus {
            get {
                return ResourceManager.GetString("deliveryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 更改 的本地化字符串。
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 編輯商品 的本地化字符串。
        /// </summary>
        internal static string editProduct {
            get {
                return ResourceManager.GetString("editProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 ID 的本地化字符串。
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 圖片 的本地化字符串。
        /// </summary>
        internal static string img {
            get {
                return ResourceManager.GetString("img", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string introduce {
            get {
                return ResourceManager.GetString("introduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否開放 的本地化字符串。
        /// </summary>
        internal static string isOpen {
            get {
                return ResourceManager.GetString("isOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 等級 的本地化字符串。
        /// </summary>
        internal static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 庫存預警 的本地化字符串。
        /// </summary>
        internal static string lowStock {
            get {
                return ResourceManager.GetString("lowStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 會員管理員 的本地化字符串。
        /// </summary>
        internal static string memberAdmin {
            get {
                return ResourceManager.GetString("memberAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 會員系統 的本地化字符串。
        /// </summary>
        internal static string memberSystem {
            get {
                return ResourceManager.GetString("memberSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 子類型 的本地化字符串。
        /// </summary>
        internal static string minorCategories {
            get {
                return ResourceManager.GetString("minorCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 名稱 的本地化字符串。
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 否 的本地化字符串。
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 開啟 的本地化字符串。
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 訂單編號 的本地化字符串。
        /// </summary>
        internal static string orderId {
            get {
                return ResourceManager.GetString("orderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 訂單狀態 的本地化字符串。
        /// </summary>
        internal static string orderStatus {
            get {
                return ResourceManager.GetString("orderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 訂單系統 的本地化字符串。
        /// </summary>
        internal static string orderSystem {
            get {
                return ResourceManager.GetString("orderSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 電話 的本地化字符串。
        /// </summary>
        internal static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 價格 的本地化字符串。
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商品 的本地化字符串。
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商品管理員 的本地化字符串。
        /// </summary>
        internal static string productAdmin {
            get {
                return ResourceManager.GetString("productAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商品ID 的本地化字符串。
        /// </summary>
        internal static string productId {
            get {
                return ResourceManager.GetString("productId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商品圖示 的本地化字符串。
        /// </summary>
        internal static string productImg {
            get {
                return ResourceManager.GetString("productImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商品英文描述 的本地化字符串。
        /// </summary>
        internal static string productIntroduceEN {
            get {
                return ResourceManager.GetString("productIntroduceEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商品中文描述 的本地化字符串。
        /// </summary>
        internal static string productIntroduceTW {
            get {
                return ResourceManager.GetString("productIntroduceTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商品英文名稱 的本地化字符串。
        /// </summary>
        internal static string productNameEN {
            get {
                return ResourceManager.GetString("productNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商品名稱搜尋 的本地化字符串。
        /// </summary>
        internal static string productNameSelect {
            get {
                return ResourceManager.GetString("productNameSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商品中文名稱 的本地化字符串。
        /// </summary>
        internal static string productNameTW {
            get {
                return ResourceManager.GetString("productNameTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商品價格 的本地化字符串。
        /// </summary>
        internal static string productPrice {
            get {
                return ResourceManager.GetString("productPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 庫存量 的本地化字符串。
        /// </summary>
        internal static string productStock {
            get {
                return ResourceManager.GetString("productStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商品系統 的本地化字符串。
        /// </summary>
        internal static string productSystem {
            get {
                return ResourceManager.GetString("productSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 商品類型 的本地化字符串。
        /// </summary>
        internal static string productType {
            get {
                return ResourceManager.GetString("productType", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 密碼 的本地化字符串。
        /// </summary>
        internal static string pwd {
            get {
                return ResourceManager.GetString("pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已取貨 的本地化字符串。
        /// </summary>
        internal static string received {
            get {
                return ResourceManager.GetString("received", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 減少庫存量 的本地化字符串。
        /// </summary>
        internal static string reduceStock {
            get {
                return ResourceManager.GetString("reduceStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 記住帳號 的本地化字符串。
        /// </summary>
        internal static string rememberAccount {
            get {
                return ResourceManager.GetString("rememberAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已退貨 的本地化字符串。
        /// </summary>
        internal static string returned {
            get {
                return ResourceManager.GetString("returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 退貨中 的本地化字符串。
        /// </summary>
        internal static string returning {
            get {
                return ResourceManager.GetString("returning", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 申請退貨 的本地化字符串。
        /// </summary>
        internal static string returnn {
            get {
                return ResourceManager.GetString("returnn", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 角色 的本地化字符串。
        /// </summary>
        internal static string roles {
            get {
                return ResourceManager.GetString("roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查詢 的本地化字符串。
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 訂購者 的本地化字符串。
        /// </summary>
        internal static string serialNumber {
            get {
                return ResourceManager.GetString("serialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 已發貨 的本地化字符串。
        /// </summary>
        internal static string shipped {
            get {
                return ResourceManager.GetString("shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 發貨中 的本地化字符串。
        /// </summary>
        internal static string shipping {
            get {
                return ResourceManager.GetString("shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 登出 的本地化字符串。
        /// </summary>
        internal static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 庫存 的本地化字符串。
        /// </summary>
        internal static string stock {
            get {
                return ResourceManager.GetString("stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 超級管理員 的本地化字符串。
        /// </summary>
        internal static string superAdmin {
            get {
                return ResourceManager.GetString("superAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 歡迎登入後台系統 的本地化字符串。
        /// </summary>
        internal static string title1Default {
            get {
                return ResourceManager.GetString("title1Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新增帳號 的本地化字符串。
        /// </summary>
        internal static string titleAddUser {
            get {
                return ResourceManager.GetString("titleAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改帳號 的本地化字符串。
        /// </summary>
        internal static string titleEditUser {
            get {
                return ResourceManager.GetString("titleEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 登入頁面 的本地化字符串。
        /// </summary>
        internal static string titleLogin {
            get {
                return ResourceManager.GetString("titleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 會員帳號 的本地化字符串。
        /// </summary>
        internal static string titleMember {
            get {
                return ResourceManager.GetString("titleMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 訂單 的本地化字符串。
        /// </summary>
        internal static string titleOrder {
            get {
                return ResourceManager.GetString("titleOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 管理員帳號 的本地化字符串。
        /// </summary>
        internal static string titleUser {
            get {
                return ResourceManager.GetString("titleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 總金額 的本地化字符串。
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 總花費 的本地化字符串。
        /// </summary>
        internal static string totalSpent {
            get {
                return ResourceManager.GetString("totalSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 請輸入帳號 的本地化字符串。
        /// </summary>
        internal static string txbAccount {
            get {
                return ResourceManager.GetString("txbAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 請輸入密碼 的本地化字符串。
        /// </summary>
        internal static string txbPassword {
            get {
                return ResourceManager.GetString("txbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 管理員ID 的本地化字符串。
        /// </summary>
        internal static string userId {
            get {
                return ResourceManager.GetString("userId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 錢包 的本地化字符串。
        /// </summary>
        internal static string wallet {
            get {
                return ResourceManager.GetString("wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 預警值 的本地化字符串。
        /// </summary>
        internal static string warningValue {
            get {
                return ResourceManager.GetString("warningValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是 的本地化字符串。
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
