CREATE LOGIN [SH_USER]
    WITH PASSWORD = N'nb.fld!+yy{vosaEtszrbYqcmsFT7_&#$!~<sg|oorjVcZrz', SID = 0x07D56BA1BC8CF140BBC6C97BD19C0582, DEFAULT_DATABASE = [ShoppingWeb], DEFAULT_LANGUAGE = [简体中文], CHECK_EXPIRATION = ON;

